### ISSUE TITLE
can you guide to me how to solve this?

### ISSUE THREAD

**Issue by bravojun7** [sammachin/AlexaPi#101]
after boot a few minutes later there is no connection between alexa. How can i solve it..?
==================================================================================
![alexa_log](https://cloud.githubusercontent.com/assets/8638121/16363431/c9af8632-3c04-11e6-96fc-88a822601b5e.png)

**Comment by flooie** [comment]
Internet issues on your part?

**Comment by bravojun7** [comment]
no. our internet work well.  and at first it can well communicate alexa
sever but after a minutue latee it can not communicate .
2016. 6. 27. 오전 1:33에 "flooie" <notifications@github.com>님이 작성:
