### ISSUE TITLE
Syntax Error in creds.py

### ISSUE THREAD

**Issue by hemingweb** [sammachin/AlexaPi#110]
Having generated the amazon refresh_token. I ran the main.py script and received a SyntaxError: invalid syntax, crews.py line 10. 

This isn't going smoothly, any suggestions?

![screen shot 2016-07-28 at 22 48 21](https://cloud.githubusercontent.com/assets/3269818/17230740/e741811c-5515-11e6-8b52-0cd0470142b8.png)

**Comment by maso27** [comment]
You've got more than one "refresh_token" in there.  

Delete the second one, and you should be good!

**Comment by hemingweb** [comment]
cheers, I had only checked the start and end of the in nano.
