### ISSUE TITLE
Client is not authorised to connect to Serverxbc_connection_has_error()

### ISSUE THREAD

**Issue by hemingweb** [sammachin/AlexaPi#111]
Hi,

Where would I starting to diagnose this issue?

Cheers

![screen shot 2016-07-29 at 07 32 23](https://cloud.githubusercontent.com/assets/3269818/17239854/2015f4d4-555f-11e6-90da-1cfda960b558.png)

**Comment by hemingweb** [comment]
I had installed zero conf and connect to the pi using screen sharing on my mac. Not sure if it relevant, is this a tightvnc issue?

**Comment by maso27** [comment]
I've never seen that error, but it might be worth trying to use SSH instead of tightvnc.

AlexaPi runs fine on Debian Jessie Lite, so I've never tried it with a desktop environment.
You could see if it happens when you ssh in as root and then run it.

**Comment by hemingweb** [comment]
Thank you for your help 

I don't get the this error using shh
