### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by moviemanic** [sammachin/AlexaPi#112]
Is there a way to add a timer functionality to AlexaPi? Amazon has a page detailing how it should work but I don't have enough expience to implement it. https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/timers-and-alarms-conceptual-overview

**Comment by renekliment** [comment]
To do this, we'd need to switch over to the new API version, which we'll do in the new upstream: https://github.com/alexa-pi/AlexaPi ... some people are already looking at it.
Not relevant for this repo -> closing.
