### ISSUE TITLE
Is TuneIn Radio Working?

### ISSUE THREAD

**Issue by GadgetReactor** [sammachin/AlexaPi#120]
Hi I just loaded 1.1 and was trying to play a TuneIn Radio channel. Did they change the format? I am getting a NoneType error. Thank you.

**Comment by sammachin** [comment]
Whats the name of the station, from what I've found their format varies so I've had to put workarounds in for many of them. you could try `play bbc radio one on tune in` as a test command

**Comment by 123icebuggy** [comment]
When I do that, it says `BBC Radio on Tune in`, then does nothing...

**Comment by GadgetReactor** [comment]
Thanks. Looks like the tunein playlist is a mess. I was able to get BBC Radio One to play. @123icebuggy I had to make one change though. - to stop the audioplaying check. 

`
		while(GPIO.input(button)==0): # we keep recording while the button is pressed
`
`
			if audioplaying: p.stop() # moved this down
`

**Comment by 123icebuggy** [comment]
What about Triple J?

Thanks anyway, I was able to get it to work, but your way seems faster
