### ISSUE TITLE
You alexa device is currently offline

### ISSUE THREAD

**Issue by 123icebuggy** [sammachin/AlexaPi#122]
I want to control Alexa from my phone, but it thinks it is offline...

Sorry to clog this issues page, I really do like what you've done.

**Comment by tangowhisky37** [comment]
Sam - I have a similar issue. My Pi is definitely logged in and connected, I am able to press the button and talk to Alexa. However, the web interface (alexa.amazon.com) says that i am offline.

Am sure there's something different in the way we've setup the pi and use the python code you've developed. When using the reference java application the web interface (alexa.amazon.com) does show the device as online.

Able to help us out here with what changes might be required?

**Comment by maso27** [comment]
AlexaPi always reports as being "offline."  It's not an issue.  It's a function of the way the system works, only sending audio files to Amazon when there's something worth sending.

Other systems maintain an always-on server that is connected to Amazon.  They register as being "online."

**Comment by sammachin** [comment]
Yeah this is mostly due to us still using the V1 Alexa API, once we get onto the V20160217 api and have a persistent HTTP/2 connection things like pushing from the app will become possible, might not work right away though!

**Comment by 123icebuggy** [comment]
Would an ETA on that be available? Also could you look at this https://github.com/sammachin/AlexaPi/issues/123 issue

**Comment by renekliment** [comment]
We're very probably gonna do this on the [new repo](https://github.com/alexa-pi/AlexaPi) only. You can check it out in the meantime.
