### ISSUE TITLE
ImportError: No module named alsaaudio

### ISSUE THREAD

**Issue by jaydev1997** [sammachin/AlexaPi#124]
File "main.py", line 7, in <module>
    import alsaaudio
ImportError: No module named alsaaudio

**Comment by 123icebuggy** [comment]
Please confirm you are using `python` and not python3`

**Comment by matthewtholt** [comment]
I'm getting the same error. definitely using python. @jaydev1997  did you get this sorted?

**Comment by jaydev1997** [comment]
@MRedRaider Yes i tried configured Audio Channels in Alsa and it sorted out... first confirm that you have Alsa with ```alsamixer```

**Comment by coach0742** [comment]
So I'm having this same issue and I can't figure out what is wrong. I have already modified main.py with the device name outputted by arecord -L, I have tested the mic with arecord and am getting input just fine. But every time I try to start up main.py, I get this error.

**Comment by jaydev1997** [comment]
which python version do you have? @coach0742

**Comment by MRedRaider** [comment]
I'm going to admit my mistake here, I'm working on a CHIP, followed that repo and when I googled this error got here and didn't think twice since I also have this running on a RPI sitting beside it. Sorry!

**Comment by jaydev1997** [comment]
@MRedRaider Oh..thats ok mate...
