### ISSUE TITLE
creds.py missing config.. refresh_token

### ISSUE THREAD

**Issue by Sparklehart** [sammachin/AlexaPi#126]
can you add in code to add this to the creds.py?
`
refresh_token = ''
`

**Comment by 123icebuggy** [comment]
Why don't you manually add it?

**Comment by sammachin** [comment]
@Sparklehart the refresh token is generated and added to the creds file by running the auth_web.py script and going throught the auth process with amazon.

**Comment by Sparklehart** [comment]
Oh. That makes sense. I switched the setup files for the ones in beta and they worked perfect. Thanks!

**Comment by renekliment** [comment]
Seems like fixed -> closing. Reopen if needed.
