### ISSUE TITLE
When running python main.py

### ISSUE THREAD

**Issue by gabbinn** [sammachin/AlexaPi#127]
I get connection ok but then 

It takes some time but she says "hello" after 10 long seconds

MemCached: MemChache: inet:127.0.0.1:11211: connect: [Errno 111] Connection refused. Marking dead

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
