### ISSUE TITLE
Objc version

### ISSUE THREAD

**Issue by flooie** [sammachin/AlexaPi#128]
I wasn't sure where to put this question, but I built an objective-c Mac version of this tool - and was wondering if anyone is interested in working on the project with me.  Right now it takes text and voice inputs but is a bit buggy with pause and resume.  Just wanted to gauge interest before I put it up.

<img width="434" alt="screen shot 2016-09-09 at 8 53 25 am" src="https://cloud.githubusercontent.com/assets/6464529/18387497/f2ade164-766a-11e6-8912-02da8fb434b5.png">

**Comment by maso27** [comment]
Sounds interesting--how are you doing the text?  TTS, then sending a wav file?

Sadly, I'm not available to work on it--too many time obligations of late.  But here's hoping you have luck with it!

**Comment by flooie** [comment]
Spot on @maso27 - Cocoa frameworks allow for silent text to speech file - which gets covered to wav and sent off.  I posted the framework minus my amazon auth keys. if you wanted it for your own use

**Comment by renekliment** [comment]
Unfortunately, I don't have a Mac to even test this. Best of luck with it though.
The new AlexaPi should however support OS X when it's ready. Let's see where the future takes us :-)

**Comment by flooie** [comment]
@renekliment the current alexapi already works on my Mac - I rewrote it in objc because I wanted an interface.

**Comment by renekliment** [comment]
@flooie Have you tried doing the GUI in python for the current project? What's the advantage of doing it in pure ObjectiveC? (speed?)
Also, I'm curious what is your use case that you want a GUI. Would you share?

**Comment by flooie** [comment]
@renekliment I did a number of things - and I released the Mac Echo (Mecho) on my github account.  I did build a version that ran the python version with objc before I decided to build it purely in objc.  It worked fine enough.  I did not build a python gui for the Mac version just the hybrid.
