### ISSUE TITLE
Issues playing tunein stations

### ISSUE THREAD

**Issue by interbiznw** [sammachin/AlexaPi#131]
Not sure why it won't play most stations but heres some output:

https://gist.github.com/interbiznw/374ad9366e5fb139de7db212c3f9a7f8

Also just got this trying to play " CBC Radio One Vancouver" On tune in:

https://gist.github.com/interbiznw/28c62a887f1cdd7e7707aeb0822f3b86

**Comment by sammachin** [comment]
TuneIn seems to be very broken right now I'm even getting errors on my Amazon hardware (TAP and Echo) I think they are moving stuff around ready for the UK/DE launch of the Echo this week. 

I'd sit tight and I'll report back when its working on the Amazon HW then we can look into AlexaPi issues.

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
