### ISSUE TITLE
Snowboy - Microphone after VAD

### ISSUE THREAD

**Issue by factulas** [sammachin/AlexaPi#132]
@maso27

> `INFO:snowboy:Keyword 1 detected at time: 2016-09-15 06:20:10
> rm: cannot remove ‘/home/pi/AlexaPi/tmpcontent/_’: No such file or directory
> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
> Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
> Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
> Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
> Checking Internet Connection...
> Connection OK
> Ready to hear your voice Press Ctrl+C to exit
> check
> Traceback (most recent call last):
>   File "/home/pi/AlexaPi/start.py", line 39, in <module>
>     sleep_time=0.03)
>   File "/home/pi/AlexaPi/snowboydecoder.py", line 190, in start
>     main.start(triggerword=True)
>   File "/home/pi/AlexaPi/main.py", line 660, in start
>     if triggerword: silence_listener()
>   File "/home/pi/AlexaPi/main.py", line 517, in silence_listener
>     frames_per_buffer=VAD_PERIOD)
>   File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
>     stream = Stream(self, *args, *_kwargs)
>   File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in **init**
>     self._stream = pa.open(**arguments)
> IOError: [Errno Device unavailable] -9985

`
Seems its not recognizing the microphone. Maybe because snowboy is not releasing it after the trigger. HELP
Edit: Formatting

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
