### ISSUE TITLE
IOError: [Errno Device unavailable] -9985

### ISSUE THREAD

**Issue by WillBishop** [sammachin/AlexaPi#137]
Using Flooie's voice-command fork, I get this error

Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
Traceback (most recent call last):
  File "start.py", line 37, in <module>
    sleep_time=0.03)
  File "/home/pi/Desktop/VOICETEST/AlexaPi/snowboydecoder.py", line 190, in start
    main.start()
  File "/home/pi/Desktop/VOICETEST/AlexaPi/main.py", line 61, in start
    recordAudio()
  File "/home/pi/Desktop/VOICETEST/AlexaPi/main.py", line 82, in recordAudio
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in **init**
    self._stream = pa.open(**arguments)
IOError: [Errno Device unavailable] -9985

**Comment by Galtwise** [comment]
Did you ever get anywhere with that? I'm in the same boat

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
