### ISSUE TITLE
AVS Adds Hands-Free Capabilities with API Update

### ISSUE THREAD

**Issue by interbiznw** [sammachin/AlexaPi#138]
Great news!

![image](https://cloud.githubusercontent.com/assets/16450422/19159841/a66552ae-8ba2-11e6-8e2f-6ced76d807bb.png)

**Comment by 123icebuggy** [comment]
Well, it is good news, but not current for AlexaPi.

If I remember correctly, there are two API versions, 1 and 2. Sammachin is working to bring API 2, because it would GREATLY improve the AlexaPi.

So let's see how it goes!

**Comment by interbiznw** [comment]
with what amazon released It looks like voice activation is done through a 3rd party app (https://snowboy.kitt.ai/)

**Comment by renekliment** [comment]
As @123icebuggy pointed out it's good news, but currently doesn't concern AlexaPi at all.

If you want voice activation, checkout the new upstream for this project: https://github.com/alexa-pi/AlexaPi 
Until we add snowboy/pyaudio support there, you can check out Mason's repo: https://github.com/maso27/AlexaPi/tree/snowboy
