### ISSUE TITLE
alsaaudio.ALSAAudioError: Device or resource busy [plughw:CARD=Device,DEV=0]

### ISSUE THREAD

**Issue by souto93** [sammachin/AlexaPi#142]
Hello everyone.
I've been stuck with this for days... 
I'd appreciate any help , this is very frustating.

pi@raspberrypi:~/Downloads/AlexaPi $ sudo python main.py
Checking Internet Connection...
Connection OK
Traceback (most recent call last):
  File "main.py", line 497, in <module>
    start()
  File "main.py", line 397, in start
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, device)
alsaaudio.ALSAAudioError: Device or resource busy [plughw:CARD=Device,DEV=0]

This is what i get from arecord -L

null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=Device
    USB PnP Sound Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Front speakers
surround21:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample mixing device
dsnoop:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct sample snooping device
hw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Direct hardware device without any conversions
plughw:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Hardware device with all software conversions

And this is what i get from arecord -l

***\* List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by souto93** [comment]
I'm connecting via USB a headhphones with microphone, in the same USB.
The model is : Trust GTX 340

**Comment by Ierlandfan** [comment]
I-ve setup the audio (Bluetooth JBL GO) through this 
https://bbs.nextthing.co/t/guide-to-connecting-to-a-bluetooth-speaker/4684/2
Works for the Raspberry Pi (2) at least. For now I have a PS3 Eye as microphone and a Bluetooth speaker as output device. Works better than HDMI.

**Comment by jtotham** [comment]
I had this problem until I turned off the graphical desktop, with my Pi configured to boot just to the console (sudo raspi-config). Might not be practical for all but if you're building a headless voice activated system then having the GUI loaded is just a waste of resources.

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
