### ISSUE TITLE
TuneIn Radio Playback

### ISSUE THREAD

**Issue by schmeckles22** [sammachin/AlexaPi#147]
Hello,

I ask to play a TuneIn radio and I get the reply -

Recording Finished.
[7113ec40] ts demux error: cannot peek
Ready to Record.
[6bd02eb0] ts demux error: cannot peek
[70bbd260] ts demux error: cannot peek

and then it will keep printing that to the terminal, Other features work and I can hear Alexa just fine.

My USB microphone has a built in sound jack that could cause it? How do I disable the sound jack on the microphone completely.

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
