### ISSUE TITLE
Wrong location?

### ISSUE THREAD

**Issue by mgeilich** [sammachin/AlexaPi#151]
Alexa thinks I am in Seattle with regards to weather, time, etc.  My Pi has the correct time.  How do I get Alexa configured for my current location?

**Comment by flooie** [comment]
are you sure you aren't in seattle?

**Comment by maso27** [comment]
:)

You need to run the Alexa app on either IOS or Android.  You can change your location settings there.  Seattle is the default.

**Comment by renekliment** [comment]
Or you can change it in the web app: https://alexa.amazon.com
