### ISSUE TITLE
Alexa stops working after interrupting

### ISSUE THREAD

**Issue by GamefreakSenpai** [sammachin/AlexaPi#153]
Whenever i interrupt Alexa on something like TuneIn Radio she stops listening for her Keyword.
sudo journalctl -u AlexaPi.service says:

Dec 08 16:20:04 alexa systemd[1]: Starting Alexa client for all your devices...
Dec 08 16:20:04 alexa systemd[1]: Started Alexa client for all your devices.
Dec 08 16:32:17 alexa python[3074]: [b4912480] core access error: connection failed: Connection refused
Dec 08 16:32:18 alexa python[3074]: [b4912480] http access: Raw-audio server found, mp3 demuxer selected
Dec 08 16:36:30 alexa systemd[1]: Stopping Alexa client for all your devices...
Dec 08 16:38:00 alexa systemd[1]: AlexaPi.service stop-sigterm timed out. Killing.
Dec 08 16:38:00 alexa systemd[1]: AlexaPi.service: main process exited, code=killed, status=9/KILL
Dec 08 16:38:00 alexa systemd[1]: Stopped Alexa client for all your devices.
Dec 08 16:38:00 alexa systemd[1]: Unit AlexaPi.service entered failed state.

**Comment by renekliment** [comment]
You're doing this in the wrong repo. Please open the issue in the correct one. Thank you.
