### ISSUE TITLE
USB Microphone resource busy problem...

### ISSUE THREAD

**Issue by peshko** [sammachin/AlexaPi#155]
I have seen multiple requests in that matter. I tried to update the config, etc. Still, I constantly get resource busy...

Traceback (most recent call last):
  File "/opt/AlexaPi/src/main.py", line 587, in <module>
    loop()
  File "/opt/AlexaPi/src/main.py", line 505, in loop
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, config['sound']['input_device'])
alsaaudio.ALSAAudioError: Device or resource busy [plughw:CARD=Device,DEV=0]

It works for a little bit, but then I get this error.

The output of arecord -l

card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

Obviously, it tries to restart itself multiple times...Works for a bit and then kicks the error again...

If I stop the service I can record and hear my recordings.

Not sure why it happens.

Any help to solve this frustrating issue is appreciated

**Comment by renekliment** [comment]
Hey. You're at the wrong repo.
Also, you probably have PulseAudio (and probably in user-session mode) running, that occupies your sound card.
