### ISSUE TITLE
main.py resource busy, failing line 126

### ISSUE THREAD

**Issue by datafaust** [sammachin/AlexaPi#159]
I've been working on getting together the chip ECHO setup courtesy of the following post which piggy backs off AlexaPI code:

http://www.instructables.com/id/An-Echo-Device-Using-the-CHIP-9-Computer/?ALLSTEPS

I've run into an issue towards the end. I am getting the following error upon running "sudo python3 main.py". Alexa says "Hello" and then she crashes when I press a button to record, the following error pops up:

ALSA lib pcm_params.c:2162:
(snd1_pcm_hw_refine_slave)
Slave PCM not usable
Traceback (most recent call last):
**File "main.py", line 126, in <module>
inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL)
alsaaudio.ALSAAudioError: Invalid argument [default]

I've replaced the main.py file with[ jitto's edits](https://github.com/jitto/AlexaCHIP/blob/04230bfb33de856a7b17983555bce74035909042/main.py) as instructed ro be able to ustilize USB Microphone, and tested the audio recording and playback on "test.wav", audio is crisp and clear and microphone seems to work fine. Any ideas how I can begin to troubleshoot?

**Comment by renekliment** [comment]
Hey. Let's not bother with the old code. Try the new upstream: https://github.com/alexa-pi/AlexaPi
