### ISSUE TITLE
Goes into a 'hello' loop after restarting services

### ISSUE THREAD

**Issue by amit4111989** [sammachin/AlexaPi#160]
Takes some amount of trial and error to get it to work after installing.

Board : RaspberryPi 3 model B

did sudo service AlexaPi restart. It keeps on saying hello without waiting for response.

**Comment by renekliment** [comment]
Are you using the new repo? See the Notes section here: https://github.com/alexa-pi/AlexaPi/wiki/Debugging#notes

Closing as irrelevant for this repo.
