### ISSUE TITLE
UnboundLocalError: local variable 'audio' referenced before assignment

### ISSUE THREAD

**Issue by Nauttor** [sammachin/AlexaPi#19]
Hi, 

Sometimes after i speak the AlexaPi crash with the following error. 

Traceback (most recent call last):
  File "/root/AlexaPi/main.py", line 157, in <module>
    start()
  File "/root/AlexaPi/main.py", line 121, in start
    alexa()
  File "/root/AlexaPi/main.py", line 95, in alexa
    f.write(audio)
UnboundLocalError: local variable 'audio' referenced before assignment

**Comment by sammachin** [comment]
Thats usually because the request wasn't understood by alexa so she didn't respond with any audio just a generic error, I 'shoud' be trapping those but I'll check in the next build
