### ISSUE TITLE
Trigger Word

### ISSUE THREAD

**Issue by tomforti** [sammachin/AlexaPi#22]
Do you have any plans to try and use a trigger word to activate the AVS in place of a button. I understand AVS doesn't directly support that and you would need to use another voice service on top of the AVS but it would be cool.

**Comment by arch1v1st** [comment]
+1!

**Comment by lennysh** [comment]
Amazon will not allow the use of a trigger word with the API.

Please close this issue.

**Comment by doubledrat** [comment]
for those of you that don't want a button, I've managed to get it working with an IR remote instead.  I'm still pressing a button, but at least it's one where I can be the other side of the room.

**Comment by lennysh** [comment]
Very nice feature indeed...
