### ISSUE TITLE
alexa app?

### ISSUE THREAD

**Issue by doubledrat** [sammachin/AlexaPi#26]
this works great, thanks for sharing mate!

is it possible to integrate with the alexa app though?  I can't work out how to do it as it seems to require a real echo to go through the setup.

any pointers would be great

thanks again.

**Comment by lennysh** [comment]
It doesn't require a real echo.  It just takes a little bit to show up in the app.  If you are showing it now, can you please close this issue?

**Comment by doubledrat** [comment]
yes, for anyone else experiencing this, it does take a very long time but eventually shows up in the app.  it was next day for me.
