### ISSUE TITLE
Alexa's Response is Missing Information

### ISSUE THREAD

**Issue by MiniguyBrendan** [sammachin/AlexaPi#28]
Hi,

I set up AlexaPi on my pi B+. Works great, thanks.

I only really have one thing that doesn't work as described: When I ask for information, it tends to give me the shortest answer possible, i.e.

"Alexa, what is anonymous?" "Anonymous: the hacking group."
"Alexa, what's the news?" "News from TuneIn."

Both responses stopped exactly there, and offered no more information. Is this not fixable, or does it have to do with how the response JSON is parsed?

Thanks.

**Comment by lennysh** [comment]
Please try my music-patch-1 branch on my fork of this project.  Posted it this morning. You'll need to look at the setup.sh of the same branch for my updated requirements installed. Also pay attention to the requirements.txt changes.

**Comment by MiniguyBrendan** [comment]
Thanks, it's a little better now. When I ask for the news, it responds with my "flash briefing," but only tells me the weather before ending the response.

Thoughts?

**Comment by lennysh** [comment]
This was working the other day. Still looking into this one.

**Comment by flooie** [comment]
Any word on this ?  I'm experiencing the same issue.

**Comment by sammachin** [comment]
I'm refactoring the whole response parser for v1.1 which should iterate through multiple objects, please sit tight and retest with 1.1 which should be ready soon
