### ISSUE TITLE
Poor Audio Play Back

### ISSUE THREAD

**Issue by RamblingGeekUK** [sammachin/AlexaPi#30]
When I play hello.mp3 using omxplayer all is loud and clear, when running main.py, very low with a hiss over the top.... 

Any suggestions?

Thanks,
Wayne

**Comment by lennysh** [comment]
You using this branch or my music-patch-1 branch?

**Comment by RamblingGeekUK** [comment]
This branch/orginal, shall I use yours then?

**Comment by lennysh** [comment]
Mine supports playing music and such. It also uses VLC to play the audio instead of mpg123.

**Comment by lennysh** [comment]
You just need to pay attention to the new requirements

**Comment by RamblingGeekUK** [comment]
I've just used yours and the output is the same... I find it odd the audio playback is so bad...

**Comment by RamblingGeekUK** [comment]
OK if I run main.py without SUDO output is via the USB sound and quality is good, if I run with SUDO output is via analogue and quality is bad.

**Comment by RamblingGeekUK** [comment]
now the script hasn't got rights to right the recording.wav file

**Comment by RamblingGeekUK** [comment]
mpg123 seems to be responsible for my poor audio play back.

**Comment by RamblingGeekUK** [comment]
OK... I increased the sound quality using "alsamixer" - forehead slap

**Comment by lennysh** [comment]
You can change the output device in my version of the script.
