### ISSUE TITLE
Should I need to edit auth_web.py?

### ISSUE THREAD

**Issue by princezordar** [sammachin/AlexaPi#32]
Thanks to the other messages here, I managed to get the Alexa files installed and working. Only hitch I ran into is auth_web kept trying to run the server on 0.0.0.0. I had to manually edit the file to include the IP address of my RaspPi. Is this normal, or does this mean I missed something?

Once I edited it, the web access works, I am just still waiting for the Amazon access to be approved.

-Z

**Comment by sammachin** [comment]
0.0.0.0 is shorthand for 'all interfaces' it should work fine with that but if you've got something else running on say localhost listening on port 5000 then that could be your issue.

It will work fine using your Pi's IP address just if the IP changes you'll have to edit.

You should only need the webserver once for the auth, after that its done
