### ISSUE TITLE
Red led and Green led connections

### ISSUE THREAD

**Issue by iacos** [sammachin/AlexaPi#37]
I'm a noobie. 

I don't have a dual led. I am using separate red and green LEDs from an old PC case. They were used as HDD and POWER indicators. They should be fine, I guess. 

On the instructions it says: "... you could also use separate LEDS, Red is connected to GPIO 24 and green to GPIO 25."

Does that mean RED is GPIO 24 + GROUND, right? The same question goes for GREEN too.

Dumb question?!

**Comment by doubledrat** [comment]
yes.  and ideally you should also use an appropriate resistor if you want the LEDs to last.  "Appropriate" very much depends on the LED's characteristics, which I'm asssuming you won't know!

PS LED's need to be wired the correct way around or they won't work

**Comment by iacos** [comment]
All clear. Thank you.
