### ISSUE TITLE
Mic volume to be increased

### ISSUE THREAD

**Issue by iacos** [sammachin/AlexaPi#38]
Noobie here. I have got Alexa running with [Amazon's git](https://github.com/amzn/alexa-avs-raspberry-pi/issues) that was all over the news the other day. I can't wait to have it running again but now with an actual push button.

I am using it with a webcam as a mic and it works fine. The only problem is that I have to speak really close to the cam/mic (less than half a meter), otherwise it won't "hear me". Is there any way to increase the volume/level of the microphone so it can hear me from 2-3 meters, let's say? 

Thanks.

**Comment by doubledrat** [comment]
yes, use

sudo alsamixer

although on mine it exits when I try to select recording with [f4]

> --

cheers
Bob
