### ISSUE TITLE
Initiate listening with swiping hand over HC-SR04 ultrasonic sensor

### ISSUE THREAD

**Issue by marksev1** [sammachin/AlexaPi#45]
Perhaps an idea for a more streamlined listening initiation would be to swipe hand over a HC-SR04 ultrasonic sensor and it would initiate listening for predefined time. Anyone up for implementing it? :)

Or maybe make it like that when you are in front of it in the "beam" of the ultrasonic sensor it listens to you and when you move away it tells the answer.

**Comment by ProfessionalParanoid** [comment]
Yup, it's on my todo list.  I have my Alexa integrated into a magic mirror with a motion sensor already working the monitor screen blanking.  I'm thinking I'll add a second one inside, back set behind a small hole in the mirror frame so you'll have to wave specifically in front that small hole to trigger. We'll see how it works out.

**Comment by marksev1** [comment]
Awesome looking forward to it. Do you have the magic mirror code also hosted somewhere?

**Comment by ProfessionalParanoid** [comment]
I used this one as a starting point: http://michaelteeuw.nl/tagged/magicmirror but used nginx vice apache.  also got rid of the random accolade in the center.  mirror and alexa in action:  http://other.bagpipez.com/Projects

**Comment by marksev1** [comment]
This is so cool. Need to build one too :D

**Comment by sammachin** [comment]
There's lots of different ideas for triggering the recording, ultrasonic sensors are quite a cool idea:)

I think I need to find a way to implement a generic interface for control and lights that then allows people to create plugins to support whatever controller they like. I'll close this for now and look at it as part of a wider concept.
