### ISSUE TITLE
Responding back without a button push

### ISSUE THREAD

**Issue by rdurrance** [sammachin/AlexaPi#57]
Hi there,
This is an awesome project. I like it better than the one using the java client. Is there a way to not have to press the button when Alexa needs a response? For instance, if I ask her to set a calender event, she will ask me when, where, etc until she is done and I say yes.  Every time I need to respond, I have to press the button.  Where are you handling responses back from the AVS? This would be a nice addition to an already great project.
-Rob

**Comment by sammachin** [comment]
Interesting point Rob, however the button does two things, one is starting the recording which could be done automatically depending on the response but the other is stopping the recording which is equally important, this would need some additional code to do silence detection and then a lot of tuning.

Right now the parsing of the response meta data is pretty crude, I'm working on a version that incorporates some music patches but after that I'll be moving over to the brand new v2 API.
I'll look into it for the V2 api as I think that might have silence detection server side as well which could help.
