### ISSUE TITLE
Stuck at "Connection OK"

### ISSUE THREAD

**Issue by cgioconda** [sammachin/AlexaPi#59]
When I run "sudo python main.py" I get the following output on the screen:
Checking Internet Connection
Connection OK

...and that's it. From other folks, it seems I should be seeing "Ready to Record". Any idea what's happening?

**Comment by sammachin** [comment]
Do you hear 'Hello' Through the speaker and have 3 flashes of the playback LED?

If so then its ready to go, just press and hold the button then say your command.

Not sure where the Ready to Record line came from, might be in another fork but I just tested the current version and Connection OK is the last thing printed to the screen.
