### ISSUE TITLE
Sonos

### ISSUE THREAD

**Issue by sureshrink** [sammachin/AlexaPi#60]
I too have several Sonos speakers and would like to use them as my Alexa speaker. I would also like to be able to control the Sonos system from AlexaPi to request music, stations and books. Can you share your code you use to control your Sonos speaker system and/or include it in 1.1 or 2.0 as an option for those who have Sonos?

**Comment by sammachin** [comment]
Yep the sonos output code should make it into a release soon, I just need to refactor the code into smaller more manageable files so it doesn't get too huge!

I'm not sure yet if it will be possible to send the music output to sonos or if that would need to be done via a skill.
