### ISSUE TITLE
Your device is currently off line...

### ISSUE THREAD

**Issue by sureshrink** [sammachin/AlexaPi#61]
When I try to set up Prime Music, Audible and other music from the Alexa app I get the off line message and am unable to set up the music. Other than that my AlexaPi works perfectly. Is this a function of having to push the button to make Alexa active? Can it be fixed? It blocks a significant amount of functionality.

**Comment by sammachin** [comment]
The online/offline functionality is a feature of the new v2016 AVS API, this has some pretty major changes under the hood, specifically it runs over http/2.

My plan is to get a 1.1 release of AlexaPi out ASAP with some basic music functionality (from the device not the app) and an improved install experience. Maybe a 1.2 with some more manageable code chunks to allow for optional setups like sonos output, different LED and button configurations then I'll start on v2 with the new API
