### ISSUE TITLE
Does this work with Philips Hue?

### ISSUE THREAD

**Issue by benblb** [sammachin/AlexaPi#63]
Does this implementation work correctly with Philips Hue without using IFTTT as a workaround?

The official Amazon implementation does not: https://github.com/amzn/alexa-avs-raspberry-pi

Thanks!

**Comment by sammachin** [comment]
I don't have a hue to test with but I expect the Echo/Hue integration uses something to connect directly within your LAN from the Echo to the Hue bridge instead of a 'cloud to cloud' connection, therefore this won't work currently with AlexaPi.

**Comment by doubledrat** [comment]
I would expect the same Sam.  Although Ben, if you can program it is
possible to write your own smart home skill that calls back to your house
and operates your equipment.  I've integrated about 4 technologies this way
that aren't natively supported.

On Thu, Apr 28, 2016 at 9:20 AM Sam Machin <notifications@github.com> wrote:

> I don't have a hue to test with but I expect the Echo/Hue integration uses
> something to connect directly within your LAN from the Echo to the Hue
> bridge instead of a 'cloud to cloud' connection, therefore this won't work
> currently with AlexaPi.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sammachin/AlexaPi/issues/63#issuecomment-215347604>
>
-- 

cheers
Bob

**Comment by dony71** [comment]
below is java based hue bridge emulator and i test it's not working with AlexaPi
it needs echo devices to discover this emulator
https://github.com/bwssytems/ha-bridge

**Comment by doubledrat** [comment]
no, it won't work as AlexaPi doesn't have the code to discover and interact with smart home devices
