### ISSUE TITLE
Do not hardcode Alsa Playback device

### ISSUE THREAD

**Issue by KonstantinSchubert** [sammachin/AlexaPi#66]
This bug report concerns the branches version1.1 and lennysh-music-patch-1.

The main.py contains the following line:
```
i = vlc.Instance('--aout=alsa', '--alsa-audio-device=hw:CARD=Device,DEV=0')
```
which hardcodes the alsa audio device. 

I was using a usb audio card and the audio therefore was not playing.

I suggest to replace the line by
```
i = vlc.Instance('--aout=alsa')
```
which means that also uses the card which is configured by the system. 

Alternatively one could offer an optional configuration option where users can specify their audio device.

**Comment by sammachin** [comment]
Good catch, I've been basing the 1.1 branch on Lenny's work with  the vlc stuff as that handles music better. Will change in 1.1 now. The music patch 1 branch is just for my reference.
