### ISSUE TITLE
Correct GPIO pinout

### ISSUE THREAD

**Issue by Tiqni** [sammachin/AlexaPi#83]
"A push to make button connected between GPIO 18 and GND"
This made me a headache, I couldn't understand why my setup is not working...

After trying each GPIO, I understood that it means "BCM 18" which is GPIO 12 pin.
(I'm using Raspberry Pi 3)

BTW, the same remark for the other LED:
GPIO 24 --> BCM 24 --> GPIO 18
GPIO 25 --> BCM 25 --> GPIO 22

**Comment by benwoodley** [comment]
If you need it to use a different pin then just change it in the main.py file, the pin is GPIO 18. GPIO 18 is pin 12 on the Pi 3. I don't think there is any difference between the pins on pi 2 and 3. The Pi 3 has very little design differences, just speed and wifi ect.
Use the diagram below for reference.
![pi3_gpio](https://cloud.githubusercontent.com/assets/17747505/15317061/c1970158-1c17-11e6-83f5-857d47bc0f11.png)

**Comment by sammachin** [comment]
The Naming is pretty clear IMO  and the project also contains a digram showing the wiring, closing.
