### ISSUE TITLE
Main.py Doesn't run with Python 3

### ISSUE THREAD

**Issue by chiragd** [sammachin/AlexaPi#9]
I guess the code was written for python2. I'm using python 3.

I'm bypassing the start procedure (because the writing of audio fails) and calling alexa method instead. Referencing a local recording.wav file I created using the command line.

I've managed to get most of it working however I'm stuck reading the response from Amazon.

File "main.py", line 103, in alexa
    data = r.content.split(boundary)
TypeError: Type str doesn't support the buffer API

Would appreciate a nudge in the right direction.

Thanks!

**Comment by Macksi** [comment]
i’m stuck at the same problem. did you manage to solve it by now?

**Comment by chiragd** [comment]
Yes u rewrite entirely for pythin 3

**Comment by Macksi** [comment]
Would you mind if i take a look at your code? Can't get it done yet.

**Comment by chiragd** [comment]
Be my guest. Will have to send it to you later. It's a bit of a mess. It
only runs once because I didn't have a button. Then you have to interrupt
it and try again. It does work though :)

C

**Comment by Macksi** [comment]
thanks a lot!

**Comment by chiragd** [comment]
Will try in the evening. Can you email me ?

**Comment by sammachin** [comment]
Currently still targettig with Python 2.7.9 for this, is there a good reason you need support for 3?

**Comment by chiragd** [comment]
I'm running other things on the Pi such as https://github.com/home-assistant/home-assistant

You can write home assistant skill's for alexa so I wanted to use alexa to turn lights on and off and more.
