### ISSUE TITLE
Port to OS X

### ISSUE THREAD

**Issue by flooie** [sammachin/AlexaPi#90]
I successfully ported the code to my Mac yesterday.  I'd like to build a nice toolbar interface and also execute it with the voice accessibility features.  Has anyone every merged apple script and python or objective-c/swift and python?

**Comment by renekliment** [comment]
Since this is 5 months old, I'm closing this. Feel free to reopen or open a PR with a link in README if you have anything active on this.

**Comment by renekliment** [comment]
There is actually #128 open with info, so no need to mourn over this empty issue :-)
