### ISSUE TITLE
Not able to capture input

### ISSUE THREAD

**Issue by architv** [sammachin/AlexaPi#92]
I have been able to setup Alexa. I have both the LED's working and I get the "Hello" from Alexa when I boot my Pi and also the red LED blinks three times. The only problem is that it doesn't capture the input. 

When I close the switch, both the LED's get lit up but three LED waits for around 2 seconds, blinks three times and then goes off, while the red LED continues to blink. This happens every time I close the switch. 

This is from `main.py`:

```
button = 18 #GPIO Pin with button connected
lights = [24, 25] # GPIO Pins with LED's conneted
device = "plughw:CARD=Device" # Name of your microphone/soundcard in arecord -L
```

I have tried `plughw:1` and `plughw:0` with no difference. I am able to record audio using `plughw:1` and my microphone works fine otherwise.

This is the output from `arecord -L`:

```
pi@raspberrypi ~ $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
sysdefault:CARD=Device
    USB PnP Sound Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    Front speakers
surround40:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB PnP Sound Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output

```

Since everything else works fine, I suspect its not able to capture the input. Any help regarding this?

**Comment by chilinski** [comment]
On two recent projects, I created some really strange results using push button switches. On one with an Arduino, I accidentally swapped a NO switch with a NC switch. Since I was looking for a "change" and not just on or off, it really messed things up (the software didn't care if the switch was on or off, just that it had changed state from on to off or off to on). Also,  on a button box for sim racing I made, I overheated a switch while soldering the leads to it and that changed it from NO to NC.

**Comment by renekliment** [comment]
Do you still have issues with this?

**Comment by renekliment** [comment]
This project is now deprecated in favor of the new AlexaPi (https://github.com/alexa-pi/AlexaPi) which has all the features of this project and much more, such as:
- support for a wide range of devices and platforms (Raspberry Pi, CHIP, Orange Pi, desktops, Magic Mirror and others)
- voice activation (great PocketSphinx support and snowboy support soon to be released)
- much more robust installation and configuration
- better security
- Arch Linux support
- awesome documentation
- and much, much more! You get it - it's just awesome.

Please switch over to the new project and if your issue persists there, file an issue in the new repo's issue tracker. Thank you.
